version: '3.7'
services:
  web:
    build: ./project
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 7000
    volumes:
      - ./project:/usr/src/app
    ports:
      - 7000:7000
    env_file: .env
